name: st. trill
favicon: null
layout_spectrum: 0.9583160746842623
typography_spectrum: 0.48596077784895897
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.8818404462654144
  lightness: 0.6356408793944865
  saturation: 0.7484413108322769
  rhythmicContrast: 0.337928609456867
purpose: []
